name: tests

on:
  push:
    branches:
      - main
      - '*x'
    tags:
      - '*'
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@9f1fedda61294df4c004c05519a3fbf3b8e1f32f  # v2.3.1
    with:
      libraries: |
        apt:
          - libopenblas-dev
      envs: |
        - linux: py311-xdist
        - linux: py312-xdist
        - linux: py313-cov-xdist
        - macos: py313-xdist
